table_dico = {'jean paul aboucaya': 'table 1 : Classic Martini',
 'pierre aboucaya': 'table 1 : Classic Martini',
 'patricia aboucaya': 'table 1 : Classic Martini',
 'danielle aboucaya': 'table 1 : Classic Martini',
 'laurence pleskoff': 'table 1 : Classic Martini',
 'robert benchetrit': 'table 1 : Classic Martini',
 'alain pleskoff': 'table 1 : Classic Martini',
 'lisette pleskoff': 'table 1 : Classic Martini',
 'michael rozental': 'table 1 : Classic Martini',
 'pascale rozental': 'table 1 : Classic Martini',
 'laura temmam': 'table 2 : Sidecar',
 'mickael temmam': 'table 2 : Sidecar',
 'pascale azoulay': 'table 2 : Sidecar',
 'philippe azoulay': 'table 2 : Sidecar',
 'cathy blacharz': 'table 2 : Sidecar',
 'bruno blacharz': 'table 2 : Sidecar',
 'laurent kuperstich': 'table 2 : Sidecar',
 'sabrina kuperstich': 'table 2 : Sidecar',
 'michele akoun': 'table 3: Caipirinha',
 'martial careme': 'table 3: Caipirinha',
 'danielle bar hen': 'table 3: Caipirinha',
 'jacky bar hen': 'table 3: Caipirinha',
 'carole ancona': 'table 3: Caipirinha',
 'eric zdanowski': 'table 3: Caipirinha',
 'annie friedman': 'table 3: Caipirinha',
 'henri mselati': 'table 3: Caipirinha',
 'patrice akoun': 'table 4 : Bloody Mary',
 'jean drapp': 'table 4 : Bloody Mary',
 'caroline drapp': 'table 4 : Bloody Mary',
 'olivier darmon': 'table 4 : Bloody Mary',
 'sandrine darmon': 'table 4 : Bloody Mary',
 'jean pierre kesselman': 'table 4 : Bloody Mary',
 'sophie kesselman': 'table 4 : Bloody Mary',
 'richard constantini': 'table 4 : Bloody Mary',
 'nathalie constantini': 'table 4 : Bloody Mary',
 'laurence kimann': 'table 5 : Sangria',
 'didier kimann': 'table 5 : Sangria',
 'patrick bellalou': 'table 5 : Sangria',
 'martine bellalou': 'table 5 : Sangria',
 'nathalie bitton': 'table 5 : Sangria',
 'david bitton': 'table 5 : Sangria',
 'moise anoufa': 'table 5 : Sangria',
 'fabienne anoufa': 'table 5 : Sangria',
 'nathalie hochberg': 'table 5 : Sangria',
 'bruno hochberg': 'table 5 : Sangria',
 'charles naim': 'Table 6 : Old Fashioned',
 'paule naim': 'Table 6 : Old Fashioned',
 'hubert sitbon': 'Table 6 : Old Fashioned',
 'yafa sitbon': 'Table 6 : Old Fashioned',
 'michele schwok': 'Table 6 : Old Fashioned',
 'bernard schwok': 'Table 6 : Old Fashioned',
 'murielle sitbon': 'Table 6 : Old Fashioned',
 'mathieu ganem': 'Table 7 : Bramble',
 'diane ganem': 'Table 7 : Bramble',
 'karine sitbon': 'Table 7 : Bramble',
 'bruno levefre': 'Table 7 : Bramble',
 'annette wezrther': 'Table 7 : Bramble',
 'jean bernard werther': 'Table 7 : Bramble',
 'celine schwok': 'Table 7 : Bramble',
 'bernard bitan': 'Table 7 : Bramble',
 'laurence boccara': 'Table 8 :Mango Mule',
 'roland boccara': 'Table 8 :Mango Mule',
 'myriam bentata': 'Table 8 :Mango Mule',
 'laurent bentata': 'Table 8 :Mango Mule',
 'nathalie goldenberg': 'Table 8 :Mango Mule',
 'dori goldenberg': 'Table 8 :Mango Mule',
 'sylvie bismuth': 'Table 8 :Mango Mule',
 'stephane bellaiche': 'Table 8 :Mango Mule',
 'johanna cattan': 'Table 8 :Mango Mule',
 'marco naim': 'Table 9 : Long island',
 'sophie naim': 'Table 9 : Long island',
 'gary fhima': 'Table 9 : Long island',
 'deborah fhima': 'Table 9 : Long island',
 'corinne chemla': 'Table 9 : Long island',
 'elisa soussan': 'Table 9 : Long island',
 'nadia schwok': 'Table 9 : Long island',
 'maurice meckler': 'Table 9 : Long island',
 'fred juris': 'Table 10 : Tom collins',
 'virginie juris': 'Table 10 : Tom collins',
 'harry oiknine': 'Table 10 : Tom collins',
 'murielle oiknine': 'Table 10 : Tom collins',
 'jean philippe mesguich': 'Table 10 : Tom collins',
 'corinne mesguich': 'Table 10 : Tom collins',
 'serge partouche': 'Table 10 : Tom collins',
 'sylvie partouche': 'Table 10 : Tom collins',
 'jacky weitzman': 'Table 10 : Tom collins',
 'dalia wietzman': 'Table 10 : Tom collins',
 'david blacharz': 'Table 11 : Sex on the beach',
 'nathan blacharz': 'Table 11 : Sex on the beach',
 'franck careme': 'Table 11 : Sex on the beach',
 'anne sophie boisy': 'Table 11 : Sex on the beach',
 'arthur drapp': 'Table 11 : Sex on the beach',
 'florian careme': 'Table 11 : Sex on the beach',
 'carla haddad': 'Table 11 : Sex on the beach',
 'ilana temmam': 'Table 11 : Sex on the beach',
 'samuel temmam': 'Table 11 : Sex on the beach',
 'adam azoulay': 'Table 11 : Sex on the beach',
 'shaili azoulay': 'Table 12 : Elderflower',
 'victoire blacharz': 'Table 12 : Elderflower',
 'megane careme': 'Table 12 : Elderflower',
 'gaelle bar hen': 'Table 12 : Elderflower',
 'yoann bar hen': 'Table 12 : Elderflower',
 'yanniv bar hen': 'Table 12 : Elderflower',
 'reut levy': 'Table 12 : Elderflower',
 'julie aboucaya': 'Table 12 : Elderflower',
 'pauline aboucaya': 'Table 12 : Elderflower',
 'johana mesguich': 'Table 12 : Elderflower',
 'noam taieb': 'Table 13 : Lychee cosmo',
 'lola sclar': 'Table 13 : Lychee cosmo',
 'maxime khaski': 'Table 13 : Lychee cosmo',
 'lola sadoun': 'Table 13 : Lychee cosmo',
 'samuel sadoun': 'Table 13 : Lychee cosmo',
 'alon fitoussi': 'Table 13 : Lychee cosmo',
 'carla abbou': 'Table 13 : Lychee cosmo',
 'sherel allouche': 'Table 13 : Lychee cosmo',
 'eleana giaoui': 'Table 13 : Lychee cosmo',
 'ilan dreyfuss': 'Table 13 : Lychee cosmo',
 'emma franco': 'Table 13 : Lychee cosmo',
 'elsa pariente': 'Table 13 : Lychee cosmo',
 'lucien fermaud': 'Table 13 : Lychee cosmo',
 'ilana toledano': 'Table 13 : Lychee cosmo',
 'gary rozental': 'Table 14 : HUGO',
 'ilana rozental': 'Table 14 : HUGO',
 'yoel melka': 'Table 14 : HUGO',
 'lola zaluski': 'Table 14 : HUGO',
 'ethan naim': 'Table 14 : HUGO',
 'francois blot': 'Table 14 : HUGO',
 'camille bourreau': 'Table 14 : HUGO',
 'alice lepre': 'Table 14 : HUGO',
 'jane latron': 'Table 14 : HUGO',
 'lea charier': 'Table 14 : HUGO',
 'arthur samuel': 'Table 15 : MAI TAI',
 'nathan sellam': 'Table 15 : MAI TAI',
 'william sitruk': 'Table 15 : MAI TAI',
 'simon nakache': 'Table 15 : MAI TAI',
 'jonas nakache': 'Table 15 : MAI TAI',
 'raphael akoun': 'Table 15 : MAI TAI',
 'alexandra bartoli': 'Table 15 : MAI TAI',
 'mathis schpindel': 'Table 15 : MAI TAI',
 'cynthia ohayon': 'Table 15 : MAI TAI',
 'ornella ohayon': 'Table 15 : MAI TAI',
 'phoebe kamioner': 'Table 15 : MAI TAI',
 'leava cohen': 'Table 15 : MAI TAI',
 'stella sadat': 'Table 15 : MAI TAI',
 'naomie rubbin': 'Table 15 : MAI TAI',
 'ronny levy': 'Table 15 : MAI TAI',
 'raphael marciano': 'Table 15 : MAI TAI',
 'benjamin sebbah': 'Table 15 : MAI TAI',
 'ethan cohen': 'Table 15 : MAI TAI',
 'daniel zaluski': 'Table 15 : MAI TAI',
 'mickael zalus': 'Table 15 : MAI TAI',
 'chiara hazan': 'Table 15 : MAI TAI',
 'anais corcos': 'Table 15 : MAI TAI',
 'fdida betsalel': 'Table 15 : MAI TAI',
 'margot amsellem': 'Table 15 : MAI TAI',
 'margaux levi': 'Table 16 : Gin Tonic',
 'leo slama': 'Table 16 : Gin Tonic',
 'john evan karcenty': 'Table 16 : Gin Tonic',
 'lea azoulay': 'Table 16 : Gin Tonic',
 'clara azoulay': 'Table 16 : Gin Tonic',
 'harry kesselman': 'Table 16 : Gin Tonic',
 'steeve kesselman': 'Table 16 : Gin Tonic',
 'maud aboucaya': 'Table 16 : Gin Tonic',
 'serge aboucaya': 'Table 16 : Gin Tonic',
 'andie karcenty': 'Table 16 : Gin Tonic',
 'ilan ruimy': 'Table 17 : Tequila Sunrise',
 'alexandre boccara': 'Table 17 : Tequila Sunrise',
 'keren fitoussi': 'Table 17 : Tequila Sunrise',
 'axel chekly': 'Table 17 : Tequila Sunrise',
 'justine gontier': 'Table 17 : Tequila Sunrise',
 'maxime laik': 'Table 17 : Tequila Sunrise',
 'andrea desbordes': 'Table 17 : Tequila Sunrise',
 'benjamin cohen': 'Table 17 : Tequila Sunrise',
 'samuel cohen': 'Table 17 : Tequila Sunrise',
 'dinah cohen': 'Table 17 : Tequila Sunrise',
 'sacha haddida': 'Table 18 : Peach Bellini',
 'ilana haddida': 'Table 18 : Peach Bellini',
 'david elsa cohen': 'Table 18 : Peach Bellini',
 'elsa cohen': 'Table 18 : Peach Bellini',
 'nathan sitbon': 'Table 18 : Peach Bellini',
 'nina sitbon': 'Table 18 : Peach Bellini',
 'leah molin': 'Table 18 : Peach Bellini',
 'mathias molin': 'Table 18 : Peach Bellini',
 'leslie sitbon': 'Table 19 Lillet',
 'gilbert ohayon': 'Table 19 Lillet',
 'olivier faivre': 'Table 19 Lillet',
 'nicole faivre': 'Table 19 Lillet',
 'didier samuel': 'Table 19 Lillet',
 'catherine samuel': 'Table 19 Lillet',
 'gaby amar': 'Table 19 Lillet',
 'yafa amar': 'Table 19 Lillet',
 'eric wanono': 'Table 19 Lillet',
 'nadine wanono': 'Table 19 Lillet',
 'raphael soussan': 'Table 20 : Dark and Stormy',
 'jasmine ganem': 'Table 20 : Dark and Stormy',
 'david niazy': 'Table 20 : Dark and Stormy',
 'talia kuperstich': 'Table 20 : Dark and Stormy',
 'sacha kuperstich': 'Table 20 : Dark and Stormy',
 'evane levy': 'Table 20 : Dark and Stormy',
 'eitan anidjar': 'Table 20 : Dark and Stormy',
 'eve naim': 'Table 20 : Dark and Stormy',
 'sacha mamou': 'Table 20 : Dark and Stormy',
 'candice darmon': 'Table 20 : Dark and Stormy',
 'patrick levy': 'table 21 : Pina Colada',
 'sandrine cohen': 'table 21 : Pina Colada',
 'thierry levy': 'table 21 : Pina Colada',
 'patrick malek': 'table 21 : Pina Colada',
 'lior levy': 'table 21 : Pina Colada',
 'orly levy': 'table 21 : Pina Colada',
 'david missistrano': 'table 21 : Pina Colada',
 'sabine mamou': 'table 21 : Pina Colada',
 'isaac mamou': 'table 21 : Pina Colada',
 'mendy lachkar': 'Table 22 : Sea Breeze',
 'mouchky lachkar': 'Table 22 : Sea Breeze',
 'haya mottal': 'Table 22 : Sea Breeze',
 'mendy mottal': 'Table 22 : Sea Breeze',
 'jordan ohayon': 'Table 22 : Sea Breeze',
 'chanel ohayon': 'Table 22 : Sea Breeze',
 'aharon lachkar': 'Table 22 : Sea Breeze',
 'nicole levy': 'table 23 : Cosmopolitan',
 'marc slama': 'table 23 : Cosmopolitan',
 'chantal slama': 'table 23 : Cosmopolitan',
 'martine israel': 'table 23 : Cosmopolitan',
 'roland israel': 'table 23 : Cosmopolitan',
 'henry azoulay': 'table 23 : Cosmopolitan',
 'edith azoulay': 'table 23 : Cosmopolitan',
 'leon ohayon': 'table 23 : Cosmopolitan',
 'joelle ohayon': 'table 23 : Cosmopolitan',
 'aline bellaiche': 'table 23 : Cosmopolitan',
 'nicole cordier': 'table 24 : Blue Hawaiian',
 'corinne darmon': 'table 24 : Blue Hawaiian',
 'patrice darmon': 'table 24 : Blue Hawaiian',
 'patrick mikowsky': 'table 24 : Blue Hawaiian',
 'ariane le cae': 'table 24 : Blue Hawaiian',
 'raphy knafo': 'table 24 : Blue Hawaiian',
 'sabine vilaplana knafo': 'table 24 : Blue Hawaiian',
 'brigitte knofer': 'table 24 : Blue Hawaiian',
 'maurice mechiche': 'table 24 : Blue Hawaiian',
 'alexandre israel': 'table 25 : Daiquiri',
 'marie laure israel': 'table 25 : Daiquiri',
 'ilan chemla': 'table 25 : Daiquiri',
 'zoe chemla': 'table 25 : Daiquiri',
 'benjamin benoliel': 'table 25 : Daiquiri',
 'matisse benoliel': 'table 25 : Daiquiri',
 'yoni taieb': 'table 25 : Daiquiri',
 'sharon taieb': 'table 25 : Daiquiri',
 'adrien israel': 'table 25 : Daiquiri',
 'yael israel': 'table 25 : Daiquiri',
 'jeremy darmon': 'table 26 : Cinderella',
 'noemie darmon': 'table 26 : Cinderella',
 'lionel mikowsky': 'table 26 : Cinderella',
 'willis mikowsky': 'table 26 : Cinderella',
 'sandrine mikowsky': 'table 26 : Cinderella',
 'evelyne mikowsky': 'table 26 : Cinderella',
 'laurie cohen': 'table 26 : Cinderella',
 'david laurie cohen': 'table 26 : Cinderella',
 'dov darmon': 'table 26 : Cinderella',
 'gwendal chapron': 'table 26 : Cinderella',
 'pascal kamioner': 'Table 27 : Moscow Mule',
 'sandrine kamioner': 'Table 27 : Moscow Mule',
 'emmanuel cohen': 'Table 27 : Moscow Mule',
 'florence cohen': 'Table 27 : Moscow Mule',
 'elisabeth anidjar': 'Table 27 : Moscow Mule',
 'joseph anidjar': 'Table 27 : Moscow Mule',
 'samy bellaiche': 'Table 27 : Moscow Mule',
 'isabelle amar': 'Table 27 : Moscow Mule',
 'sabine cohen': 'Table 27 : Moscow Mule',
 'avy cohen': 'Table 27 : Moscow Mule',
 'jonhathan dhery': 'Table 28 : Aperol Spritz',
 'shana david': 'Table 28 : Aperol Spritz',
 'hanna bergel': 'Table 28 : Aperol Spritz',
 'eden bergel': 'Table 28 : Aperol Spritz',
 'julian levy': 'Table 28 : Aperol Spritz',
 'candice tolorenzi': 'Table 28 : Aperol Spritz',
 'elie anidjar': 'Table 28 : Aperol Spritz',
 'ruben anidjar': 'Table 28 : Aperol Spritz',
 'omry lachkar': 'Table 28 : Aperol Spritz',
 'lola levy': 'Table 29 : Strawberry Daiquiri',
 'jarod israel': 'Table 29 : Strawberry Daiquiri',
 'jacob ganem': 'Table 29 : Strawberry Daiquiri',
 'adele soussan': 'Table 29 : Strawberry Daiquiri',
 'stella maman': 'Table 29 : Strawberry Daiquiri',
 'gaidone kamioner': 'Table 30 : Mojito',
 'mahe kamioner': 'Table 30 : Mojito',
 'shirel boccara': 'Table 30 : Mojito',
 'lior mamou': 'Table 30 : Mojito',
 'elia mamou': 'Table 30 : Mojito',
 'lenny bellaiche': 'Table 30 : Mojito',
 'shaily cohen': 'Table 30 : Mojito',
 'lynoi cohen': 'Table 30 : Mojito',
 'nell bellaiche': 'Table 30 : Mojito',
 'taylor darmon soren': 'Table 30 : Mojito',
 'mickael karcenty': 'Table 31 : Screw Driver',
 'norman karcenty': 'Table 31 : Screw Driver',
 'audrey karcenty': 'Table 31 : Screw Driver',
 'annaelle karcenty': 'Table 31 : Screw Driver',
 'jessica careme': 'Table 31 : Screw Driver',
 'fabien careme': 'Table 31 : Screw Driver',
 'johana constantini': 'Table 31 : Screw Driver',
 'kevin constantini': 'Table 31 : Screw Driver',
 'stephane karcenty': 'Table 32 : Aperol Soul',
 'carole karcenty': 'Table 32 : Aperol Soul',
 'bernard mesguich': 'Table 32 : Aperol Soul',
 'daniele darmon': 'Table 32 : Aperol Soul',
 'thierry mesguich': 'Table 32 : Aperol Soul',
 'valerie mesguisch': 'Table 32 : Aperol Soul',
 'danielle temam': 'Table 32 : Aperol Soul',
 'maryline temmam': 'Table 32 : Aperol Soul',
 'laurent ohayon': 'Table 32 : Aperol Soul',
 'valerie ohayon': 'Table 32 : Aperol Soul',
 'meir lachkar': 'Table 33 : Revolver',
 'leah lachkar': 'Table 33 : Revolver',
 'esther melloul': 'Table 33 : Revolver',
 'micki melloul': 'Table 33 : Revolver',
 'arie leib lachkar': 'Table 33 : Revolver',
 'sterna lachkar': 'Table 33 : Revolver',
 'dan lachkar': 'Table 33 : Revolver'}



message_dico= {'jean paul aboucaya': 'Si la musique est trop forte on connait un bon ORL',
 'pierre aboucaya': 'Lache ta raquette est viens danser',
 'patricia aboucaya': 'un ptit martini pour la route',
 'danielle aboucaya': "On est pas a Avoriaz ici on t'attends sur la piste",
 'laurence pleskoff': 'Petite partie de volley a la Salis ?',
 'robert benchetrit': 'On est pas à la Salis la viens danser',
 'alain pleskoff': "Aussi bon au volley qu'en danse ? on va voir ca ?",
 'lisette pleskoff': 'un ptit martini pour la route',
 'michael rozental': 'Montre nous ton petit déhanché',
 'pascale rozental': "Je crois que j'ai une carrie je vais boire un petit martini",
 'laura temmam': 'les rois de la danse c est les Temmam',
 'mickael temmam': 'On est pas à Serpentard ici',
 'pascale azoulay': 'Kebidou Nainai viens danser avec moi',
 'philippe azoulay': 'Viens me faire tourner comme dans space mountain',
 'cathy blacharz': 'OH CATHHHHYYYY GOULOUGOULOU',
 'bruno blacharz': 'Petit ciné à Mouans Sarthoux c est plus détente que la danse',
 'laurent kuperstich': 'KUKU c est plus simple que kuperstich',
 'sabrina kuperstich': 'KUKU c est plus simple que kuperstich',
 'michele akoun': "C'est toi que j'aime le plus mais faut pas le dire",
 'martial careme': 'Il est ou le temps ou tu me donner le bain , Ton ptit polonais est un homme',
 'danielle bar hen': 'Il parait que tu danses le tango a merveille',
 'jacky bar hen': 'Reprends un verre de caipirinha et viens danser',
 'carole ancona': "On va mettre plus le feu qu'au concert des enfoirés",
 'eric zdanowski': "Mon cousin je t'attends sur la piste",
 'annie friedman': 'la belle , le beau est un homme marié ',
 'henri mselati': 'LEHAIM',
 'patrice akoun': 'JOOOOOOOOOOHHHHHHHHHN',
 'jean drapp': 'Le plus fou est attendu sur la piste',
 'caroline drapp': 'Faut tenir Jean il danse mieux qu le HATAN',
 'olivier darmon': 'OH GRAND SPARTACUS , LEHAIM',
 'sandrine darmon': 'Un petit bloody mary pour la route ?',
 'jean pierre kesselman': 'LE vrai JOHN est la',
 'sophie kesselman': 'Tiens JP il fait des pompes sur la piste de danse',
 'richard constantini': 'On est mieux a la belote à Monax',
 'nathalie constantini': "A cause des magnums à Monax j'ai eu du mal a fermer le costume",
 'laurence kimann': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'didier kimann': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'patrick bellalou': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'martine bellalou': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'nathalie bitton': 'Petit Avoriaz pour décompresser ?',
 'david bitton': 'OHHH tu me dois un shot toi',
 'moise anoufa': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'fabienne anoufa': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'nathalie hochberg': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'bruno hochberg': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'charles naim': 'Tonton il faut prendre de la boukha',
 'paule naim': 'Tata on a kiffé Arlozorov',
 'hubert sitbon': 'Papi pas trop vite le coeur est fragile',
 'yafa sitbon': 'Lehaim',
 'michele schwok': 'Le temps ou je dormais dans le Bunker est si loin . LOVE',
 'bernard schwok': 'Petite raclette à Verbier pour feter ca ?',
 'murielle sitbon': 'A la danse Tata',
 'mathieu ganem': "L'orchestre est de qualité ce soir j'attends ton avis",
 'diane ganem': 'de Molière à Hatan... que le temps passe',
 'karine sitbon': 'Ton filleur se marie et tu laisses faire ca',
 'bruno levefre': "Thais peut t'appeler TONTON ?",
 'annette wezrther': 'Ich will ein Ball !!!!',
 'jean bernard werther': 'lisane emilie médou',
 'celine schwok': 'La meilleure danseuse de suisse est avec nous ce soir',
 'bernard bitan': 'Bienvenue dans une famille de fou , machine arriere encore possible ',
 'laurence boccara': "Besoin d'un bon crédit à taux réduit apres ce mariage",
 'roland boccara': "Alllez espoir pouusssee et n'oublie pas ton beau maillot de bain rose",
 'myriam bentata': 'SDV bientôt chez toi',
 'laurent bentata': 'AKOUNAMATATA !!!',
 'nathalie goldenberg': 'Essaye de pas tomber dans les pommes :)',
 'dori goldenberg': "C'est l'heure du LEHAIM",
 'sylvie bismuth': 'Au plaisir de repartager une pizza ensemble',
 'stephane bellaiche': 'Tonton Relou tiens toi droit',
 'johanna cattan': 'Bon courage les prochains mariés',
 'marco naim': 'OHHHHH NAAAAAAAN ANTOIIIIINE',
 'sophie naim': 'Mimiiiiiii lehaim',
 'gary fhima': 'Rameneeeeee le genep',
 'deborah fhima': "Gary va encore nous dire qu'on a mis un truc dans son verre",
 'corinne chemla': "On s'est entrainé dans le duplex alors viens danser",
 'elisa soussan': "on y est ...... La foliiie  on t'aime",
 'nadia schwok': 'Quelle soiree on a passé en suisse , objectif la meme ',
 'maurice meckler': 'Bienvenue dans une famille de fou , machine arriere encore possible',
 'fred juris': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'virginie juris': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'harry oiknine': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'murielle oiknine': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'jean philippe mesguich': 'NAAAAZZZZZZOUUUUUUUCHHHH',
 'corinne mesguich': 'NAZOUUUUUCHETTTTTTE',
 'serge partouche': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'sylvie partouche': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'jacky weitzman': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'dalia wietzman': "C'est donc ca les potes , on va voir si vous mettez vraiment le feu ",
 'david blacharz': 'OH les cousins LEHAIM',
 'nathan blacharz': 'Je split thais et Ben et je double le mariage',
 'franck careme': 'QUEL TRESOR , QU ON LUI RAMENE DE L EAU ',
 'anne sophie boisy': 'Je te prends ANN euh Thais , Thais est ta Femme',
 'arthur drapp': 'Un si beau déhanché doit venir au milieu',
 'florian careme': "J'ai demandé TEL AVIV EN BOUCLE",
 'carla haddad': 'A fond sur la piste si on vous voit pas je vous bannis',
 'ilana temmam': 'LEHAIM LA COUS',
 'samuel temmam': 'GRAND fouuuuuuu  va',
 'adam azoulay': 'Lieeeeeevreeeeee',
 'shaili azoulay': 'Miveau tu as trop grandi',
 'victoire blacharz': 'Niiiiniiii LEHAIM',
 'megane careme': "C'est le cousin qui se marie bordel , alors shooot",
 'gaelle bar hen': "C'est le cousin qui se marie bordel , alors shooot",
 'yoann bar hen': "C'est le cousin qui se marie bordel , alors shooot",
 'yanniv bar hen': "C'est le cousin qui se marie bordel , alors shooot",
 'reut levy': "C'est le cousin qui se marie bordel , alors shooot",
 'julie aboucaya': "tant de chemin et de kiff pour arriver la j'attends la photo",
 'pauline aboucaya': 'Petite soirée jeux de société après ?',
 'johana mesguich': "Attention sur l'alcool t'es mineure",
 'noam taieb': 'NONOOOOOOOOOOOOOOOOOOOOOOO',
 'lola sclar': 'On va bien manger la',
 'maxime khaski': "tu sens qu'on va passer une bonne soirée ?",
 'lola sadoun': 'Soirée très instagramable',
 'samuel sadoun': "Mieux une bonne vibora qu'un mariage",
 'alon fitoussi': 'ASPERGE',
 'carla abbou': "La diététique c'est pas pour ce soir",
 'sherel allouche': 'ON FIRE TONIGHT',
 'eleana giaoui': "Je sais que t'attends bollywood mais bon essaye de kiffer et prends un cosmo",
 'ilan dreyfuss': "Heuresement c'est pas la finale del'us open ce soir",
 'emma franco': 'Lehaim , surveille nono quand meme ',
 'elsa pariente': "ZOUZOUUUUUU si t'es pas bourée on comprends plus",
 'lucien fermaud': 'RDV 22h07 pour le shot',
 'ilana toledano': 'RDv 21h45 pour le shot',
 'gary rozental': 'SHOT ? SHOT ?',
 'ilana rozental': 'LEHAÏM !',
 'yoel melka': 'Fais pas trop le fou on te surveille , et HAPPY BIRTHDAY TO YOUUUU',
 'lola zaluski': 'on te voit regarder les hommes attention',
 'ethan naim': 'OLAAAAA le cousin est dans la place',
 'francois blot': 'Fini la biere prends la VODKAA',
 'camille bourreau': 'Il faut prendre rdv après le mariage dos bloqué assure',
 'alice lepre': 'Il faut prendre rdv après le mariage dos bloqué assure',
 'jane latron': "L'orchestre te convient ?",
 'lea charier': 'On va pas charrier ce soir alors viens danser',
 'arthur samuel': 'OUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
 'nathan sellam': 'Shot a 21h44',
 'william sitruk': "Aussi bon au foot qu'à la danse ?",
 'simon nakache': "Qu'es ce que t'es nul au Padel ",
 'jonas nakache': 'Go lézigny , fini ces conneries de mariage go gagner le 250',
 'raphael akoun': "Ca c'est un bon cochon",
 'alexandra bartoli': 'Surveille ton homme il est bourré',
 'mathis schpindel': 'Tu danses aussi bien que tu ne joues au padel',
 'cynthia ohayon': "Dernier kiff avant l'aventure , plaque diplomatiqu allez",
 'ornella ohayon': 'Madame Chou TWERK',
 'phoebe kamioner': "C'est toi la prochaine ? Allez bois ton shot !!",
 'leava cohen': "Le village de KAMANICOUN se réveil et fait la fête avant l'arrivée des loups garou",
 'stella sadat': "On t'a vu t'entrainer à la fête tout l'été rdv sur la piste ",
 'naomie rubbin': "C'est l'heure du SHOOOOT",
 'ronny levy': 'Monsieur ambiance est dans la place ',
 'raphael marciano': "Bouillant jusqu'a la fin de la nuit ",
 'benjamin sebbah': 'SKY SKY SKYYYYYYYY SHOOOOT',
 'ethan cohen': 'Tu danses aussi bien que tu joues au padel',
 'daniel zaluski': 'Promis après la fête on fait la prev',
 'mickael zalus': 'danse mais te blesse pas ce soir on a pas signé la prev',
 'chiara hazan': 'Il faut surveiller les couloirs y a des descentes',
 'anais corcos': "C'est l'heure du SHOOOOT",
 'fdida betsalel': 'LEHAIM',
 'margot amsellem': 'LEHAIM',
 'margaux levi': 'Belote en after ?',
 'leo slama': 'On va voir les pas que tu as appris à Madrid , prêt pour le flamenco',
 'john evan karcenty': "Un Karcenty déchainé c'est quelque chose",
 'lea azoulay': 'Un petit tonic ?',
 'clara azoulay': 'Shot a 22h39 ?',
 'harry kesselman': 'Les johnny se dechainent ce soir',
 'steeve kesselman': 'Les johnny se dechainent ce soir',
 'maud aboucaya': "Doucement sur l'alcool t es mineure",
 'serge aboucaya': 'On va aller lancer des oeufs sur les voitures apres',
 'andie karcenty': "Doucement sur l'alcool t es mineure",
 'ilan ruimy': 'Fais pas la pince sur le chèque on te connait',
 'alexandre boccara': 'On va très bien danser avec BOCCARA',
 'keren fitoussi': "Du coup t es du coté Thais ou Ben ? On t'attends pour le shot avec ton pref",
 'axel chekly': "Aussi fou qu'a marbella , chuuut ",
 'justine gontier': 'La der avant le canada . Alors kiiiiiiffff',
 'maxime laik': "OUHHH bordel jsuis bourré déja , si tu peux l'amener un verre d'eau en douce ",
 'andrea desbordes': 'On va montrer a Ben et MAx qui sait danser',
 'benjamin cohen': "Bravo mon Ben t'es à lheure ce soir",
 'samuel cohen': 'Maitre Cohen est attendue pour un shot Maitre cohen',
 'dinah cohen': "c'est dommage qu'il y ait plus la dote en 2023",
 'sacha haddida': "Ca me manque de t'entendre chanter dans la douche",
 'ilana haddida': 'On suit le chemin , LEhaim',
 'david elsa cohen': 'Vous nous avez ouvert la voie à nous de jouer',
 'elsa cohen': 'Vous nous avez ouvert la voie à nous de jouer',
 'nathan sitbon': 'Vous nous avez ouvert la voie à nous de jouer',
 'nina sitbon': 'Vous nous avez ouvert la voie à nous de jouer',
 'leah molin': "Tonnnn ptiooooot n'est plus un ptiot",
 'mathias molin': "Un bidonnnn d'eauuuuuu",
 'leslie sitbon': 'MIMIIII doucement sur la vodka',
 'gilbert ohayon': 'mon guilli je t attend pour la boukha',
 'olivier faivre': 'Seul représentant bedaouis on va voir si vous êtes au niveau',
 'nicole faivre': 'Seul représentant bedaouis on va voir si vous êtes au niveau',
 'didier samuel': 'Bonjour Monsieur PDG',
 'catherine samuel': "EH maintenant c'est Que du bonheur ",
 'gaby amar': 'Tabernak viens nous voir plus souvent sinon on vient ',
 'yafa amar': 'LEHAIM',
 'eric wanono': 'Désolé y a pas de Magnum au menu',
 'nadine wanono': 'Du Kiff, du Kiff et rien que du kiff',
 'raphael soussan': 'La relève est assuré ici ',
 'jasmine ganem': "La couz pas trop d'alcool t'es mineure ",
 'david niazy': 'La suisse est attendue sur la piste de danse ',
 'talia kuperstich': "La on a une danseuse attention sur l'alcool t'es mineure ",
 'sacha kuperstich': "La star de tiktok on t'attends sur la piste",
 'evane levy': 'Encore mieux que la folie douce',
 'eitan anidjar': "Oh l'économe en chef , la gestion du stock d'alcool est ta responsabilité ",
 'eve naim': 'Ma cousine chérie reste ma petite cousine a vie',
 'sacha mamou': 'Viens nous montrer ton déhanché ',
 'candice darmon': 'La petite candice est demandée sur la piste de danse ',
 'patrick levy': "AHAHAHAH T'ES KILLE ",
 'sandrine cohen': 'Je te jure on a pas pleuré :)',
 'thierry levy': 'Viens nous rendre visite plus souvent à paris , y a pas le soleil mais on est la ',
 'patrick malek': 'on nous a dit que le 3 eme tonton avait un beau déhanché',
 'lior levy': 'Captain Oh Captain',
 'orly levy': 'Oooooh champs élysées palapalapa',
 'david missistrano': 'A  la santé de Jean François',
 'sabine mamou': "Souccah avant l'heure",
 'isaac mamou': "Souccah après l'heure",
 'mendy lachkar': 'Sof sof ! Mission accomplie ! LEHAÏM !!',
 'mouchky lachkar': 'LEHAÏM !',
 'haya mottal': 'Prof efficace pour élève studieuse ! Merci et LEHAÏM !',
 'mendy mottal': 'LEHAÏM !',
 'jordan ohayon': 'LEHAÏM !',
 'chanel ohayon': 'LEHAÏM !',
 'aharon lachkar': 'LEHAÏM !',
 'nicole levy': "Un conseil baisse le son des oreillettes ce soir, Ps: on t'attend pour le debriff",
 'marc slama': 'LEHAÏM !',
 'chantal slama': 'LEHAÏM !',
 'martine israel': 'Le bronzage est bien peaufiné ?',
 'roland israel': 'Il assure ce mariage ?',
 'henry azoulay': 'Le prochain mariage chez vous sdv',
 'edith azoulay': 'Sdv, chez vous très bientôt !! ',
 'leon ohayon': 'Allez Paris Saint Germain',
 'joelle ohayon': 'LEHAÏM !',
 'aline bellaiche': 'A la fin de la soirée petit bridge si on a pas abusé de la vodka',
 'nicole cordier': 'Manque que le trampoline pour se croire à Champigny',
 'corinne darmon': 'Tiens ton mari , il est encore au bar ',
 'patrice darmon': "Attention ceci n'est pas une BAR mitsva",
 'patrick mikowsky': 'Papi Patrick est dans la place ??',
 'ariane le cae': 'LEHAÏM !',
 'raphy knafo': "On t'attend sur la piste",
 'sabine vilaplana knafo': "On t'attend sur la piste pour un cours de zumba",
 'brigitte knofer': "Si bristol n'existait pas il faudrait l'inventer",
 'maurice mechiche': 'Lehaaaaaïm !!!!',
 'alexandre israel': "On t'attend au MAAAAX",
 'marie laure israel': 'Le daiquiri vient pas de Bordeaux mais il est bon',
 'ilan chemla': "Doucement sur la piste les croisés c'est 6 mois minimum",
 'zoe chemla': 'A la tienne ma marraine chéri',
 'benjamin benoliel': 'Un ptit tour de tobogan ?',
 'matisse benoliel': 'Attention la piscine est salée',
 'yoni taieb': "Je compte sur toi pour nous faire boire de l'eau",
 'sharon taieb': 'Reste plus tard que 23h ! PARS PASSSS',
 'adrien israel': "Show us what's London have",
 'yael israel': "we don't speak english but we can dance ",
 'jeremy darmon': 'Tu veux ta revanche au ping ?',
 'noemie darmon': 'Lehaim lehaim !!',
 'lionel mikowsky': "On trinque en l'honneur du futur papa !!",
 'willis mikowsky': "On trinque en l'honneur de la future maman",
 'sandrine mikowsky': 'Le mazal se trouve peut être table MAI TAI ??? ;)',
 'evelyne mikowsky': 'Tchin Tchin Mamie Wilisky',
 'laurie cohen': 'Il a bien grandi le bébé que tu gardais',
 'david laurie cohen': 'LEHAIM lehaim !!',
 'dov darmon': "Interdit d'aller dormir avant 3h....",
 'gwendal chapron': 'Alexandra pekin express est table MAI TAI !!!',
 'pascal kamioner': 'MOSCOOOOOOOOOWWWWWW MULLLLLE',
 'sandrine kamioner': 'Tiens Pascal et pleurs pas',
 'emmanuel cohen': 'BAIAIA est mariée',
 'florence cohen': 'Un Shot pour la plus kiffeuse des Kiffeuses',
 'elisabeth anidjar': 'cops de mère en fille',
 'joseph anidjar': 'Gluten free but fun not free ',
 'samy bellaiche': "J'espère que tu as travaillé ta vibora",
 'isabelle amar': 'Un docteur est demandé sur la pite pour mettre le feu ',
 'sabine cohen': "Essaye de tenir jusqu'a 23h ,l'alcool coule à flot ",
 'avy cohen': "Lehaim Monsieur le témoin la boukha t'attend",
 'jonhathan dhery': "Mon binome d'alcool ce soir ",
 'shana david': "C'est l'heure du SHOOOOT",
 'hanna bergel': 'On a hâte de voir le bronzage ',
 'eden bergel': "C'est le moment de danser comme à TEl AVIV ",
 'julian levy': 'JUL ON FIRE ',
 'candice tolorenzi': 'LA bipolaire va montrer son bon coté ce soir ? ALORS SHOT ',
 'elie anidjar': "Après les piste de ski, on t'attend sur la piste de danse ",
 'ruben anidjar': "le décalage horaire ne va pas t'empecher de danser",
 'omry lachkar': 'LEHAIMMM',
 'lola levy': 'La cousine est attendue sur la piste ',
 'jarod israel': 'Welcome at the party ',
 'jacob ganem': 'ma star il faut danser',
 'adele soussan': 'la plus belle de la soirée est la ',
 'stella maman': 'Pas 14! ',
 'gaidone kamioner': 'Doucement sur la vodka on te surveille ',
 'mahe kamioner': 'La plus belle des kamioner est la ',
 'shirel boccara': 'BENSSSSSSSSSSHIIIII',
 'lior mamou': "Docteur love on t'attend sur la piste ",
 'elia mamou': "on t'attend sur la piste ",
 'lenny bellaiche': "Ici c'est paris !",
 'shaily cohen': 'Ce soir, tu as le droit de ne pas être sage ',
 'lynoi cohen': 'La star de la danse va mettre le feu ce soir ',
 'nell bellaiche': 'Il faut fêter le bac comme il se doit',
 'taylor darmon soren': 'Doucement avec les filles on te surveille',
 'mickael karcenty': "Oh le cousin prépare ta vue le mariage va t'éblouir ",
 'norman karcenty': "Aussi bon danseur que joueur de Padel ? j'attends de voir ca ",
 'audrey karcenty': 'La reine de la danse ? ',
 'annaelle karcenty': "C'est l'heure du SHOOOOT",
 'jessica careme': "Careme Lopater Jessica c'est l'heure de la vodka ",
 'fabien careme': 'Laisse la bétadine et mets nous sous morphine',
 'johana constantini': "T'es tellement nulle à la skob, on va voir si tu danses mieux ",
 'kevin constantini': 'OLA mesdames kevin est dans la place laissez passer',
 'stephane karcenty': 'Monsieur Karcenty est demandé sur la piste de danse ',
 'carole karcenty': "Ca c'est un bon LEHAIM",
 'bernard mesguich': "Tonton j'ai mal aux pieds dans mes chaussures ",
 'daniele darmon': "JUsqu'a 120 ans ! Lehaim",
 'thierry mesguich': 'Titouuuuu on fire ',
 'valerie mesguisch': "MAis t'es ou je te vois pas sur la pisteeeee",
 'danielle temam': 'Lehaimmmmm',
 'maryline temmam': 'Lehaimmmmm',
 'laurent ohayon': 'Représente Saint mandé sur la pisttttte',
 'valerie ohayon': 'Lehaimmmmm',
 'meir lachkar': 'LEHAÏM !',
 'leah lachkar': 'LEHAÏM !',
 'esther melloul': 'LEHAÏM !',
 'micki melloul': 'LEHAÏM !',
 'arie leib lachkar': 'LEHAÏM !',
 'sterna lachkar': 'LEHAÏM !',
 'dan lachkar': 'Tu me dois toujours une invitation à Lou Pantail'}